create table
public.sites (
  id bigint generated by default as identity,
  name text not null,
  urls text[] not null,
  created_at timestamp with time zone not null default now(),
  "queryParamsToRemove" text[] null,
  logo_url text not null,
  blacklisted_paths text[] not null default '{/}'::text[],
  provider text not null,
  deprecated boolean not null default false,
  incognito_support boolean not null default false,
  constraint sites_pkey primary key (id)
) tablespace pg_default;

create table
public.links (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  url text not null,
  title text not null,
  site_id bigint not null,
  scrape_failure_count integer not null default 0,
  last_scraped_at timestamp with time zone not null default (now() at time zone 'utc'::text),
  scrape_failure_email_sent boolean not null default false,
  ai_prompt_addition text not null default ''::text,
  constraint links_pkey primary key (id),
  constraint links_site_id_fkey foreign key (site_id) references sites (id) on update restrict on delete restrict,
  constraint links_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict
) tablespace pg_default;

-- create Job Status enum with values new, applied, archived
create type public."Job Status" as enum ('new', 'applied', 'archived', 'processing', 'excluded_by_advanced_matching', 'deleted');
create table
public.jobs (
  id bigint generated by default as identity,
  user_id uuid not null default auth.uid (),
  "externalId" text not null,
  "externalUrl" text not null,
  "siteId" bigint not null,
  title text not null,
  "companyName" text not null,
  "companyLogo" text null,
  location text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  salary text null,
  tags text[] not null default '{}'::text[],
  "jobType" text null,
  status public."Job Status" not null default 'new'::"Job Status",
  description text null,
  labels text[] not null default '{}'::text[],
  link_id bigint null,
  exclude_reason text null,
  -- set once the job has been categorized, so it is never processed twice
  processed_at timestamp with time zone null,
  -- set when a worker claims the job for description scanning
  processing_started_at timestamp with time zone null,
  -- content fingerprints, maintained by trigger_update_job_dedup_keys
  dedup_key text null,
  dedup_key_loc text null,
  constraint jobs_pkey primary key (id),
  constraint jobs_user_id_externalid_key unique (user_id, "externalId"),
  constraint jobs_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict,
  constraint jobs_siteid_fkey foreign key ("siteId") references sites (id) on update restrict on delete restrict,
  constraint public_jobs_link_id_fkey foreign key (link_id) references links (id) on update cascade on delete set null
) tablespace pg_default;
create index jobs_user_id_updated_at_id_status_idx on public.jobs (user_id, updated_at desc, id desc, status);
-- deliberately NOT unique: ON CONFLICT can only arbitrate one constraint, and a
-- violation here would abort a whole scan batch. insert_jobs_deduped serializes
-- per user with an advisory lock instead.
create index jobs_user_dedup_key_idx on public.jobs (user_id, dedup_key);
create index jobs_user_dedup_key_loc_idx on public.jobs (user_id, dedup_key_loc);

create table
public.reviews (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  title text not null,
  description text null,
  rating integer not null,
  constraint reviews_pkey primary key (id),
  constraint reviews_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict,
  constraint unique_user_review unique (user_id) -- This enforces one review per user for the app
) tablespace pg_default;

create table
public.html_dumps (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  url text not null,
  html text not null,
  webpage_runtime_data jsonb null,
  constraint html_dumps_pkey primary key (id)
) tablespace pg_default;

create table
public.notes (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  text text not null,
  files text[] not null default '{}'::text[],
  job_id bigint not null,
  constraint notes_pkey primary key (id),
  constraint notes_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint notes_job_id_fkey foreign key (job_id) references jobs (id) on update cascade on delete cascade
) tablespace pg_default;
alter table public.notes enable row level security;
create policy "enable all for users based on user_id" 
on public.notes 
as permissive 
for all 
to authenticated 
using (auth.uid() = user_id) 
with check (auth.uid() = user_id);

alter table public.sites enable row level security;
alter table public.jobs enable row level security;
alter table public.links enable row level security;
alter table public.reviews enable row level security;
alter table public.html_dumps enable row level security;
alter table public.notes enable row level security;

-- row level security
create policy "enable select for authenticated users only" 
on public.sites 
as permissive 
for select 
to authenticated 
using (true);

create policy "enable all for users based on user_id" 
on public.links 
as permissive 
for all 
to authenticated 
using (auth.uid() = user_id) 
with check (auth.uid() = user_id);

create policy "enable all for users based on user_id" 
on public.jobs 
as permissive 
for all 
to authenticated 
using (auth.uid() = user_id) 
with check (auth.uid() = user_id);

create policy "enable insert reviews for authenticated users only" 
on public.reviews 
as permissive 
for insert 
to authenticated 
with check (auth.uid() = user_id);

create policy "enable update reviews for authenticated users only"
on public.reviews
as permissive
for update
to authenticated
using (auth.uid() = user_id);

create policy "enable select reviews for authenticated users only" 
on public.reviews 
as permissive 
for select 
to authenticated 
using (auth.uid() = user_id);

create policy "enable all for users based on user_id" 
on public.html_dumps 
as permissive 
for all 
to authenticated 
using (auth.uid() = user_id) 
with check (auth.uid() = user_id);

create table
public.profiles (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  stripe_customer_id text null,
  stripe_subscription_id text null,
  subscription_end_date timestamp without time zone not null default (now() + '7 days'::interval),
  subscription_tier text not null default 'basic'::text,
  is_trial boolean not null default true,
  constraint profiles_pkey primary key (id),
  constraint profiles_user_id_key unique (user_id),
  constraint profiles_user_id_fkey foreign key (user_id) references auth.users (id) on delete restrict
) tablespace pg_default;

alter table public.profiles enable row level security;
create policy "enable select profiles for authenticated users only" 
on public.profiles 
as permissive 
for select 
to authenticated 
using (auth.uid() = user_id);

-- create custom DB functions
create or replace function list_jobs(
    jobs_status "Job Status", 
    jobs_after text, 
    jobs_page_size integer, 
    jobs_search text default null,
    jobs_site_ids integer[] default null,
    jobs_link_ids integer[] default null,
    jobs_labels text[] default null
)
returns setof jobs as $$
declare
  after_id integer;
  after_updated_at timestamp;
begin
  if jobs_after is not null then
    after_id := split_part(jobs_after, '!', 1)::integer;
    after_updated_at := split_part(jobs_after, '!', 2)::timestamp;
  end if;

  return query
  select *
  from jobs
  where user_id = auth.uid()
    and status = jobs_status
    and (jobs_after is null or (updated_at, id) < (after_updated_at, after_id))
    and (array_length(jobs_site_ids, 1) is null or "siteId" = any(jobs_site_ids))
    and (array_length(jobs_link_ids, 1) is null or link_id = any(jobs_link_ids))
    and (array_length(jobs_labels, 1) is null or labels && jobs_labels)
    and (jobs_search is null or job_search_vector @@ plainto_tsquery('english', jobs_search))
  order by updated_at desc, id desc
  limit jobs_page_size;
end; $$
language plpgsql;

create or replace function get_user_id_by_email(email text)
returns table (id uuid)
security definer
as $$
begin
  return query select au.id from auth.users au where au.email = $1;
end;
$$ language plpgsql;

-- trigger used to automatically create public.profiles for new users
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (user_id)
  values (new.id);
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- migration script
-- insert into public.profiles (user_id)
-- select id from auth.users
-- where id not in (select user_id from public.profiles);

-- Stripe DB wrappers (opt-in; disabled by default).
-- The vault.secrets insert below requires pgsodium privileges that the
-- local seed runner lacks, which aborts `supabase db reset`. The Stripe
-- FDW is not used at runtime (Stripe webhook handler uses the Node SDK),
-- so the block is wrapped in a /* */ block comment. Remove the comment
-- markers if you need the FDW locally. (psql \if metacommands are not
-- supported by `supabase db reset`'s batch protocol — block comment is
-- the portable gate.)
/*
create extension if not exists wrappers with schema extensions;
create foreign data wrapper stripe_wrapper
  handler stripe_fdw_handler
  validator stripe_fdw_validator;

insert into vault.secrets (name, secret)
values (
  'stripe_secret_key',
  'YOUR_SECRET'
)
returning key_id;

create server stripe_server
  foreign data wrapper stripe_wrapper
  options (
    api_key_id 'stripe_secret_key',
    api_url 'https://api.stripe.com/v1/'
  );

create schema stripe;
create foreign table stripe.customers (
  id text,
  email text,
  name text,
  description text,
  created timestamp,
  attrs jsonb
)
  server stripe_server
  options (
    object 'customers',
    rowid_column 'id'
  );

create foreign table stripe.subscriptions (
  id text,
  customer text,
  currency text,
  current_period_start timestamp,
  current_period_end timestamp,
  attrs jsonb
)
  server stripe_server
  options (
    object 'subscriptions',
    rowid_column 'id'
  );
*/

-- advanced matching
create table
public.advanced_matching (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  blacklisted_companies text[] not null default '{}'::text[],
  chatgpt_prompt text not null default ''::text,
  ai_api_cost double precision not null default '0'::double precision,
  ai_api_input_tokens_used double precision not null default '0'::double precision,
  ai_api_output_tokens_used double precision not null default '0'::double precision,
  dedup_mode text not null default 'company_title',
  constraint advanced_matching_pkey primary key (id),
  constraint advanced_matching_dedup_mode_check check (dedup_mode in ('off', 'company_title', 'company_title_location')),
  constraint advanced_matching_user_id_key unique (user_id),
  constraint advanced_matching_user_id_fkey foreign key (user_id) references auth.users (id) on update restrict on delete restrict
) tablespace pg_default;
alter table public.advanced_matching enable row level security;
create policy "enable all for users based on user_id" 
on public.advanced_matching 
as permissive 
for all 
to authenticated 
using (auth.uid() = user_id) 
with check (auth.uid() = user_id);

create or replace function count_chatgpt_usage(
  for_user_id uuid, 
  cost_increment numeric, 
  input_tokens_increment integer, 
  output_tokens_increment integer
) 
returns void 
language plpgsql 
as $$
begin
  update public.advanced_matching
  set 
    ai_api_cost = ai_api_cost + cost_increment, 
    ai_api_input_tokens_used = ai_api_input_tokens_used + input_tokens_increment, 
    ai_api_output_tokens_used = ai_api_output_tokens_used + output_tokens_increment
  where user_id = for_user_id;
end;
$$;

-- create search vector for jobs
alter table public.jobs
add column job_search_vector tsvector;

create or replace function update_job_search_vector()
returns trigger as $$
begin
  -- Update the job_search_vector column with weighted tsvector values
  new.job_search_vector := 
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new."companyName", '')), 'B');
  return new;
end;
$$ language plpgsql;

create trigger trigger_update_job_search_vector
before insert or update of title, "companyName" on jobs
for each row
execute function update_job_search_vector();

-- run this one time to update all existing rows
DO $$
DECLARE
  batch_size INT := 10000;
  min_id INT;
  max_id INT;
BEGIN
  -- Find the range of IDs in the table
  SELECT MIN(id), MAX(id) INTO min_id, max_id FROM public.jobs;

  -- Process in batches
  WHILE min_id <= max_id LOOP
    UPDATE public.jobs
    SET job_search_vector = 
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce("companyName", '')), 'B')
    WHERE id >= min_id AND id < min_id + batch_size;

    -- Move to the next batch
    min_id := min_id + batch_size;

    -- Optionally, log progress
    RAISE NOTICE 'Processed up to ID: %', min_id;
  END LOOP;
END $$;

create or replace function count_jobs(
    jobs_status "Job Status" default null, 
    jobs_search text default null,
    jobs_site_ids integer[] default null,
    jobs_link_ids integer[] default null,
    jobs_labels text[] default null
)
returns table(status "Job Status", job_count bigint) as $$
begin
  return query
  select j.status, count(*) as job_count
  from jobs j
  where user_id = auth.uid()
    and (jobs_status is null or j.status = jobs_status)
    and (array_length(jobs_site_ids, 1) is null or j."siteId" = any(jobs_site_ids))
    and (array_length(jobs_link_ids, 1) is null or j.link_id = any(jobs_link_ids))
    and (array_length(jobs_labels, 1) is null or labels && jobs_labels)
    and (jobs_search is null or j.job_search_vector @@ plainto_tsquery('english', jobs_search))
  group by j.status
  order by j.status;
end; $$
language plpgsql;


-- tables needed for 2025-11 release
create table public.ai_usage_daily (
  user_id uuid not null,
  usage_date date not null default CURRENT_DATE,
  cost numeric not null default 0,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  updated_at timestamp with time zone not null default now(),
  constraint ai_usage_daily_pkey primary key (user_id, usage_date),
  constraint ai_usage_daily_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete RESTRICT
) TABLESPACE pg_default;

create view public.v_ai_usage_last_30d as
select
  d.user_id,
  COALESCE(sum(d.cost), 0::numeric) as cost_last_30d,
  COALESCE(sum(d.input_tokens), 0::numeric)::bigint as input_tokens_last_30d,
  COALESCE(sum(d.output_tokens), 0::numeric)::bigint as output_tokens_last_30d
from
  ai_usage_daily d
where
  d.usage_date >= (CURRENT_DATE - '30 days'::interval)
group by
  d.user_id;

create or replace function log_ai_usage(
  for_user_id uuid, 
  cost_increment numeric, 
  input_tokens_increment bigint, 
  output_tokens_increment bigint
) 
returns void 
language plpgsql 
as $$
begin
  insert into public.ai_usage_daily (user_id, usage_date, cost, input_tokens, output_tokens)
  values (for_user_id, current_date, cost_increment, input_tokens_increment, output_tokens_increment)
  on conflict (user_id, usage_date)
  do update set
    cost = public.ai_usage_daily.cost + excluded.cost,
    input_tokens = public.ai_usage_daily.input_tokens + excluded.input_tokens,
    output_tokens = public.ai_usage_daily.output_tokens + excluded.output_tokens,
    updated_at = now();
end;
$$;


-- ============================================================================
-- Job deduplication + idempotent processing.
-- Mirrors supabase/sql/2026-08-19-job-dedup.sql, minus the one-shot backfill
-- (a fresh reset has an empty jobs table). Keep the two in sync: this file is
-- what `supabase db reset` builds, and what the data-only backups restore into.
-- ============================================================================

-- Unicode fold: lowercase, decompose to NFD and strip combining marks, then
-- map the ligatures/strokes that NFD does not decompose.
-- NOTE: normalize() MUST run before f2a_squash strips non-alphanumerics --
-- the reverse order turns 'fuer' (u-umlaut) into 'f r'.
create or replace function public.f2a_fold(txt text)
returns text language sql immutable parallel safe as $fn$
  select translate(
           replace(
             regexp_replace(normalize(lower(coalesce(txt, '')), NFD), '[\u0300-\u036f]', '', 'g'),
             'ß', 'ss'),
           'øđłþæœ', 'odltao');
$fn$;

-- Collapse to a canonical space-separated token string.
-- Keeps + and # so "C++", "C#" and ".NET" stay meaningful.
create or replace function public.f2a_squash(txt text)
returns text language sql immutable parallel safe as $fn$
  select btrim(
    regexp_replace(
      regexp_replace(coalesce(txt, ''), '[^a-z0-9+#]+', ' ', 'g'),
      '\s+', ' ', 'g'));
$fn$;

-- Title normalizer: strips gender markers and work-mode noise.
-- Uses \m / \M (word boundaries) rather than (^|[^a-z0-9]) -- the latter
-- consumes the boundary character, so adjacent markers escape under the g flag.
create or replace function public.f2a_norm_title(txt text)
returns text language sql immutable parallel safe as $fn$
  select public.f2a_squash(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          public.f2a_fold(txt),
          -- (a) bracketed / pipe-delimited noise segments
          '[\(\[\|][^\)\]\|]*(all genders?|m/w/d|w/m/d|m/f/d|f/m/d|d/f/m|m/w/x|m/f/x|w/m/x|f/m/x|d/m/w|m/w/divers|divers|gn\*?|remote|hybrid|onsite|on-site|100% remote)[^\)\]\|]*([\)\]\|]|$)',
          ' ', 'g'),
        -- (b) bare gender markers with no brackets
        '\m(m/w/d|w/m/d|m/f/d|f/m/d|m/w/x|m/f/x|w/m/x|f/m/x|gn)\M',
        ' ', 'g'),
      -- (c) standalone work-mode words anywhere
      '\m(remote|remotely|hybrid|onsite|on-site)\M',
      ' ', 'g'));
$fn$;

-- Company normalizer. Deliberately NO legal-suffix stripping (GmbH/SE/Inc/Ltd):
-- LinkedIn company names are already stable per employer, so it buys little,
-- and a \mco\M rule would maul "FetchJobs.co".
create or replace function public.f2a_norm_company(txt text)
returns text language sql immutable parallel safe as $fn$
  select public.f2a_squash(public.f2a_fold(txt));
$fn$;

create or replace function public.f2a_norm_location(txt text)
returns text language sql immutable parallel safe as $fn$
  select public.f2a_squash(public.f2a_fold(txt));
$fn$;


-- ---------------------------------------------------------------------------
-- 2. Columns, trigger, indexes
-- ---------------------------------------------------------------------------
-- Trigger rather than GENERATED ... STORED: a generated column pins its
-- expression at DDL time, so CREATE OR REPLACE on a normalizer would leave
-- stored values stale with no error. It also cannot reference another
-- generated column, so dedup_key_loc could not reuse dedup_key.
create or replace function public.update_job_dedup_keys()
returns trigger language plpgsql as $fn$
declare
  k text;
begin
  k := public.f2a_norm_company(new."companyName") || '|' || public.f2a_norm_title(new.title);
  new.dedup_key     := k;
  new.dedup_key_loc := k || '|' || public.f2a_norm_location(new.location);
  return new;
end;
$fn$;

drop trigger if exists trigger_update_job_dedup_keys on public.jobs;
create trigger trigger_update_job_dedup_keys
before insert or update of title, "companyName", location on public.jobs
for each row execute function public.update_job_dedup_keys();

create index if not exists jobs_user_dedup_key_idx
  on public.jobs (user_id, dedup_key);
create index if not exists jobs_user_dedup_key_loc_idx
  on public.jobs (user_id, dedup_key_loc);


-- ---------------------------------------------------------------------------
-- 4. Audit trail for suppressed candidates
--    "Never insert" leaves no record, so keep every skipped candidate's URL.
-- ---------------------------------------------------------------------------
create table if not exists public.job_dedup_skips (
  id bigint generated by default as identity,
  user_id uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  dedup_key text not null,
  "externalId" text not null,
  "externalUrl" text not null,
  title text not null,
  "companyName" text not null,
  location text null,
  link_id bigint null,
  kept_job_id bigint null,
  constraint job_dedup_skips_pkey primary key (id),
  constraint job_dedup_skips_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete restrict
) tablespace pg_default;

create index if not exists job_dedup_skips_user_created_idx
  on public.job_dedup_skips (user_id, created_at desc);

alter table public.job_dedup_skips enable row level security;

drop policy if exists "enable all for users based on user_id" on public.job_dedup_skips;
create policy "enable all for users based on user_id" on public.job_dedup_skips
  as permissive for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ---------------------------------------------------------------------------
-- 5. Deduplicating ingestion RPC
--    Replaces the .upsert() in scan-urls and create-link.
-- ---------------------------------------------------------------------------
create or replace function public.insert_jobs_deduped(p_jobs jsonb)
returns setof public.jobs
language plpgsql
security invoker
as $fn$
declare
  v_user uuid := auth.uid();
  v_mode text;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  select am.dedup_mode into v_mode
  from public.advanced_matching am
  where am.user_id = v_user;
  v_mode := coalesce(v_mode, 'company_title');

  -- Serialize ingestion per user so the read-existing / insert-new pair below is
  -- atomic w.r.t. sibling scan-urls invocations (jobScanner fans out over links
  -- under Promise.all). xact-scoped, so PostgREST's per-request transaction
  -- releases it automatically.
  perform pg_advisory_xact_lock(hashtextextended(v_user::text, 42));

  return query
  with payload as (
    select
      j ->> 'externalId'                as external_id,
      j ->> 'externalUrl'               as external_url,
      (j ->> 'siteId')::bigint          as site_id,
      j ->> 'title'                     as title,
      j ->> 'companyName'               as company_name,
      nullif(j ->> 'companyLogo', '')   as company_logo,
      nullif(j ->> 'location', '')      as location,
      nullif(j ->> 'salary', '')        as salary,
      nullif(j ->> 'jobType', '')       as job_type,
      coalesce((select array_agg(t)
                from jsonb_array_elements_text(coalesce(j -> 'tags', '[]'::jsonb)) t),
               '{}'::text[])            as tags,
      nullif(j ->> 'link_id', '')::bigint as link_id,
      ord
    from jsonb_array_elements(p_jobs) with ordinality as e(j, ord)
    where j ->> 'externalId' is not null
      and j ->> 'title' is not null
      and j ->> 'companyName' is not null
  ),
  keyed as (
    select p.*,
      case
        when v_mode = 'company_title_location' then
          public.f2a_norm_company(p.company_name) || '|' || public.f2a_norm_title(p.title)
            || '|' || public.f2a_norm_location(p.location)
        else
          public.f2a_norm_company(p.company_name) || '|' || public.f2a_norm_title(p.title)
      end as eff_key
    from payload p
  ),
  -- Intra-batch dedup. The 25-city fan-out arrives in ONE payload, so this is
  -- what collapses it; the cross-batch check below cannot see uncommitted rows.
  ranked as (
    select k.*, row_number() over (partition by k.eff_key order by k.ord) as rn
    from keyed k
  ),
  -- Cross-batch dedup: status-agnostic, so new / applied / archived / filtered
  -- out / deleted all block re-ingestion. This is the core requirement.
  matched as (
    select r.*,
      (select ej.id from public.jobs ej
        where ej.user_id = v_user
          and (case when v_mode = 'company_title_location'
                    then ej.dedup_key_loc else ej.dedup_key end) = r.eff_key
        order by ej.id
        limit 1) as kept_job_id
    from ranked r
  ),
  survivors as (
    select * from matched
    where v_mode = 'off'
       or (rn = 1 and kept_job_id is null)
  ),
  skipped as (
    select * from matched
    where v_mode <> 'off'
      and (rn > 1 or kept_job_id is not null)
  ),
  -- Data-modifying CTEs always run to completion even when unreferenced.
  log_skips as (
    insert into public.job_dedup_skips (
      user_id, dedup_key, "externalId", "externalUrl",
      title, "companyName", location, link_id, kept_job_id)
    select v_user, s.eff_key, s.external_id, s.external_url,
           s.title, s.company_name, s.location, s.link_id, s.kept_job_id
    from skipped s
    returning 1
  )
  insert into public.jobs (
    user_id, "externalId", "externalUrl", "siteId", title, "companyName",
    "companyLogo", location, salary, "jobType", tags, link_id, status
  )
  select v_user, s.external_id, s.external_url, s.site_id, s.title, s.company_name,
         s.company_logo, s.location, s.salary, s.job_type, s.tags, s.link_id,
         'processing'::public."Job Status"
  from survivors s
  on conflict (user_id, "externalId") do nothing
  returning *;
end;
$fn$;

grant execute on function public.insert_jobs_deduped(jsonb) to authenticated;


-- ---------------------------------------------------------------------------
-- 6. Atomic claim for the description-scan pipeline
--    Replaces listJobs({ status: 'processing' }), which re-handed the same
--    leftovers to every cron tick.
-- ---------------------------------------------------------------------------
create or replace function public.claim_jobs_for_processing(
  p_limit int default 300,
  p_stale_after interval default '15 minutes'
)
returns setof public.jobs
language plpgsql
security invoker
as $fn$
begin
  return query
  update public.jobs j
  set processing_started_at = now()
  where j.id in (
    select id from public.jobs
    where user_id = auth.uid()
      and status = 'processing'
      and (processing_started_at is null
           or processing_started_at < now() - p_stale_after)
    order by created_at asc
    limit p_limit
    for update skip locked
  )
  returning j.*;
end;
$fn$;

grant execute on function public.claim_jobs_for_processing(int, interval) to authenticated;
